spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fiarahantsika_dev?useSSL=false&serverTimezone=UTC
    username: root
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://fiarahantsikadev-nomena-feed.i.aivencloud.com:24502/defaultdb?ssl-mode=REQUIRED}
    username: ${DB_USER:avnadmin}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

---
grpc:
  client:
    predictionService:
      address: static://localhost:50051
      negotiationType: plaintext

server:
  port: 8080

logging:
  level:
    com.fiarahantsika.backend.order: DEBUG