name: CI/CD Backend
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./FiarahantsikaBackend
          file: ./FiarahantsikaBackend/Dockerfile
          push: true
          tags: arinomena/fiarahantsika-backend:latest
